// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
)

func (c Commit) MarshalJSON() ([]byte, error) {
	type Commit struct {
		PreCommits     Votes `json:"votes"    gencodec:"required"`
		FirstPreCommit *Vote `json:"vote"     gencodec:"required"`
	}
	var enc Commit
	enc.PreCommits = c.PreCommits
	enc.FirstPreCommit = c.FirstPreCommit
	return json.Marshal(&enc)
}

func (c *Commit) UnmarshalJSON(input []byte) error {
	type Commit struct {
		PreCommits     Votes `json:"votes"    gencodec:"required"`
		FirstPreCommit *Vote `json:"vote"     gencodec:"required"`
	}
	var dec Commit
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.PreCommits == nil {
		return errors.New("missing required field 'votes' for Commit")
	}
	c.PreCommits = dec.PreCommits
	if dec.FirstPreCommit == nil {
		return errors.New("missing required field 'vote' for Commit")
	}
	c.FirstPreCommit = dec.FirstPreCommit
	return nil
}
