// Code generated by mockery v1.0.0
package types

import common "github.com/kowala-tech/kUSD/common"
import mock "github.com/stretchr/testify/mock"

// MockSignedVote is an autogenerated mock type for the SignedVote type
type MockSignedVote struct {
	mock.Mock
}

// Address provides a mock function with given fields:
func (_m *MockSignedVote) Address() common.Address {
	ret := _m.Called()

	var r0 common.Address
	if rf, ok := ret.Get(0).(func() common.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	return r0
}

// Vote provides a mock function with given fields:
func (_m *MockSignedVote) Vote() *Vote {
	ret := _m.Called()

	var r0 *Vote
	if rf, ok := ret.Get(0).(func() *Vote); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Vote)
		}
	}

	return r0
}
