// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pubsub

import (
	"sync"
)

var (
	lockPublisherMockPublish sync.RWMutex
	lockPublisherMockStop    sync.RWMutex
)

// PublisherMock is a mock implementation of Publisher.
//
//     func TestSomethingThatUsesPublisher(t *testing.T) {
//
//         // make and configure a mocked Publisher
//         mockedPublisher := &PublisherMock{
//             PublishFunc: func(topic string, data []byte) error {
// 	               panic("TODO: mock out the Publish method")
//             },
//             StopFunc: func()  {
// 	               panic("TODO: mock out the Stop method")
//             },
//         }
//
//         // TODO: use mockedPublisher in code that requires Publisher
//         //       and then make assertions.
//
//     }
type PublisherMock struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(topic string, data []byte) error

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Topic is the topic argument value.
			Topic string
			// Data is the data argument value.
			Data []byte
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
}

// Publish calls PublishFunc.
func (mock *PublisherMock) Publish(topic string, data []byte) error {
	if mock.PublishFunc == nil {
		panic("PublisherMock.PublishFunc: method is nil but Publisher.Publish was just called")
	}
	callInfo := struct {
		Topic string
		Data  []byte
	}{
		Topic: topic,
		Data:  data,
	}
	lockPublisherMockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	lockPublisherMockPublish.Unlock()
	return mock.PublishFunc(topic, data)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//     len(mockedPublisher.PublishCalls())
func (mock *PublisherMock) PublishCalls() []struct {
	Topic string
	Data  []byte
} {
	var calls []struct {
		Topic string
		Data  []byte
	}
	lockPublisherMockPublish.RLock()
	calls = mock.calls.Publish
	lockPublisherMockPublish.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *PublisherMock) Stop() {
	if mock.StopFunc == nil {
		panic("PublisherMock.StopFunc: method is nil but Publisher.Stop was just called")
	}
	callInfo := struct {
	}{}
	lockPublisherMockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	lockPublisherMockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//     len(mockedPublisher.StopCalls())
func (mock *PublisherMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	lockPublisherMockStop.RLock()
	calls = mock.calls.Stop
	lockPublisherMockStop.RUnlock()
	return calls
}
