FROM node:latest

WORKDIR /kusd-netstats
ADD netstats/ .

ARG URL
ARG CDN_URL
ARG EXPLORER_URL
ARG FAUCET_URL
ARG WS_SECRET
ARG NETWORK_NAME

ENV URL $URL
ENV CDN_URL $CDN_URL
ENV EXPLORER_URL $EXPLORER_URL
ENV FAUCET_URL $FAUCET_URL
ENV WS_SECRET $WS_SECRET
ENV NETWORK_NAME $NETWORK_NAME

RUN npm install && npm audit fix

EXPOSE 3000

CMD ["npm", "start"]
