/*
Package validator implements the consensus worker

Duplicated votes

When a validator signs duplicitously, a short evidence transaction can be
generated by anyone with the two conflicting signatures. This evidence is
committed into the blockchain which destroys the bonded coins of the guilty
validator(s). As long as the evidence is committed before the guilty
validator’s coins are spent (that is, before the unbonding period is over),
the validator can be duly punished.
*/

package validator
