// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/kowala-tech/kcoin/core/types"

// VotingSystem is an autogenerated mock type for the VotingSystem type
type VotingSystem struct {
	mock.Mock
}

// Add provides a mock function with given fields: vote
func (_m *VotingSystem) Add(vote *types.Vote) error {
	ret := _m.Called(vote)

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.Vote) error); ok {
		r0 = rf(vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRound provides a mock function with given fields:
func (_m *VotingSystem) NewRound() {
	_m.Called()
}
