// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package vm

import (
	"encoding/json"
	"math/big"

	"github.com/kowala-tech/kcoin/client/common"
	"github.com/kowala-tech/kcoin/client/common/hexutil"
	"github.com/kowala-tech/kcoin/client/common/math"
)

var _ = (*structLogMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (s StructLog) MarshalJSON() ([]byte, error) {
	type StructLog struct {
		Pc                  uint64                      `json:"pc"`
		Op                  OpCode                      `json:"op"`
		ComputationalEffort math.HexOrDecimal64         `json:"compEffort"`
		ComputeUnitPrice    math.HexOrDecimal64         `json:"compUnitprice"`
		Memory              hexutil.Bytes               `json:"memory"`
		MemorySize          int                         `json:"memSize"`
		Stack               []*math.HexOrDecimal256     `json:"stack"`
		Storage             map[common.Hash]common.Hash `json:"-"`
		Depth               int                         `json:"depth"`
		Err                 error                       `json:"-"`
		OpName              string                      `json:"opName"`
		ErrorString         string                      `json:"error"`
	}
	var enc StructLog
	enc.Pc = s.Pc
	enc.Op = s.Op
	enc.ComputationalEffort = math.HexOrDecimal64(s.ComputationalEffort)
	enc.ComputeUnitPrice = math.HexOrDecimal64(s.ComputeUnitPrice)
	enc.Memory = s.Memory
	enc.MemorySize = s.MemorySize
	if s.Stack != nil {
		enc.Stack = make([]*math.HexOrDecimal256, len(s.Stack))
		for k, v := range s.Stack {
			enc.Stack[k] = (*math.HexOrDecimal256)(v)
		}
	}
	enc.Storage = s.Storage
	enc.Depth = s.Depth
	enc.Err = s.Err
	enc.OpName = s.OpName()
	enc.ErrorString = s.ErrorString()
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (s *StructLog) UnmarshalJSON(input []byte) error {
	type StructLog struct {
		Pc                  *uint64                     `json:"pc"`
		Op                  *OpCode                     `json:"op"`
		ComputationalEffort *math.HexOrDecimal64        `json:"compEffort"`
		ComputeUnitPrice    *math.HexOrDecimal64        `json:"compUnitprice"`
		Memory              *hexutil.Bytes              `json:"memory"`
		MemorySize          *int                        `json:"memSize"`
		Stack               []*math.HexOrDecimal256     `json:"stack"`
		Storage             map[common.Hash]common.Hash `json:"-"`
		Depth               *int                        `json:"depth"`
		Err                 error                       `json:"-"`
	}
	var dec StructLog
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Pc != nil {
		s.Pc = *dec.Pc
	}
	if dec.Op != nil {
		s.Op = *dec.Op
	}
	if dec.ComputationalEffort != nil {
		s.ComputationalEffort = uint64(*dec.ComputationalEffort)
	}
	if dec.ComputeUnitPrice != nil {
		s.ComputeUnitPrice = uint64(*dec.ComputeUnitPrice)
	}
	if dec.Memory != nil {
		s.Memory = *dec.Memory
	}
	if dec.MemorySize != nil {
		s.MemorySize = *dec.MemorySize
	}
	if dec.Stack != nil {
		s.Stack = make([]*big.Int, len(dec.Stack))
		for k, v := range dec.Stack {
			s.Stack[k] = (*big.Int)(v)
		}
	}
	if dec.Storage != nil {
		s.Storage = dec.Storage
	}
	if dec.Depth != nil {
		s.Depth = *dec.Depth
	}
	if dec.Err != nil {
		s.Err = dec.Err
	}
	return nil
}
